version: '3'

services:
  movies-uploads-app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
    container_name: movies-uploads-nest
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    networks:
      - uzum-network
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_pass
      POSTGRES_DB: services
    ports:
      - "5432:5432"
#
#  redis:
#          image: redis:latest
#          restart: on-failure
#          container_name: redis_container
#          ports:
#            - "6379:6379"
#          #    volumes:
#          #      - /path/to/local/d–∞ta:/root/redis
#          #      - /path/to/local/redis.conf:/usr/local/etc/redis/redis.conf
#          environment:
#            REDIS_PASSWORD: redis_pass
#            REDIS_PORT: 6379
#            REDIS_DATABASES: redis_db

networks:
  uzum-network:
    external: true
